#!/bin/bash
#
#  subod The Subo Core server.
#
#
# chkconfig: 345 80 20
# description: subod
# processname: subod
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/subod, see below
if [ -f /etc/sysconfig/subod ]; then
        . /etc/sysconfig/subod
fi

RETVAL=0

prog=subod
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/subod
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/subod}

# subod defaults to /usr/bin/subod, override with BITCOIND_BIN
subod=${BITCOIND_BIN-/usr/bin/subod}

# subod opts default to -disablewallet, override with BITCOIND_OPTS
subod_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $subod $subod_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
